In [91]:
# viewing and understanding the data
import pandas as pd
df= pd.read_csv("melb_data.csv")
df.isnull().sum()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [92]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [95]:
#cleaning headers and labels
df.rename(columns={
'lattitude': 'latitude',
    'longtitude': 'longitude',
    'landsize': 'land_size',
    'buildingarea': 'building_area',
    'yearbuilt': 'year_built',
    'councilarea': 'council_area',
    'regionname': 'region_name',
    'propertycount': 'property_count'
}, inplace=True)
df.columns
df.columns = [col.lower() for col in df.columns]
df.columns.to_list()

['suburb',
 'address',
 'rooms',
 'type',
 'price',
 'method',
 'sellerg',
 'date',
 'distance',
 'postcode',
 'bedroom2',
 'bathroom',
 'car',
 'land_size',
 'building_area',
 'year_built',
 'council_area',
 'latitude',
 'longitude',
 'region_name',
 'property_count']

In [96]:
#handling missing values
df.dropna(subset=["car"], inplace= True)
df.car.isnull().sum()
df['building_area'] = df['building_area'].fillna(df['building_area'].median())
df['building_area'].isnull().sum()
df = df.dropna(subset=['year_built'])
df = df.copy() # Explicitly make a copy to avoid SettingWithCopyWarning
df["council_area"] = df["council_area"].fillna("Other")

In [97]:
#handling data types
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y')
df['year_sold'] = df['date'].dt.year
df['month_sold'] = df['date'].dt.month
# Displaying the first few rows with the new columns for verification
print(df[['date', 'year_sold', 'month_sold']].head())

        date  year_sold  month_sold
1 2016-02-04       2016           2
2 2017-03-04       2017           3
4 2016-06-04       2016           6
6 2016-05-07       2016           5
7 2016-10-08       2016          10

In [98]:
#Categorical columns (strings everywhere)
df= pd.get_dummies(df, columns=[
   'type', 'method', 'region_name'
])

In [99]:
#logical categories cleaning
df['postcode'] = df['postcode'].astype(str)
df= df.drop(columns=['address'])

In [104]:
#final cleaning. making it ready for ML
df = df.drop(columns=[
    'suburb',
    'sellerg',
    'council_area',
    'postcode',
    'date'
], errors='ignore')
df = df.drop(columns=['type_u', 'method_PI', 'region_name_Western Victoria'], errors='ignore')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8174 entries, 1 to 13579
Data columns (total 27 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   rooms                                   8174 non-null   int64
 1   price                                   8174 non-null   float64
 2   distance                                8174 non-null   float64
 3   bedroom2                                8174 non-null   float64
 4   bathroom                                8174 non-null   float64
 5   car                                     8174 non-null   float64
 6   land_size                               8174 non-null   float64
 7   building_area                           8174 non-null   float64
 8   year_built                              8174 non-null   float64
 9   latitude                                8174 non-null   float64
 10  longitude                               8174 non-null   float64
 11  property_count                          8174 non-null   float64
 12  year_sold                               8174 non-null   int32
 13  month_sold                              8174 non-null   int32
 14  type_h                                  8174 non-null   bool
 15  type_t                                  8174 non-null   bool
 16  method_S                                8174 non-null   bool
 17  method_SA                               8174 non-null   bool
 18  method_SP                               8174 non-null   bool
 19  method_VB                               8174 non-null   bool
 20  region_name_Eastern Metropolitan        8174 non-null   bool
 21  region_name_Eastern Victoria            8174 non-null   bool
 22  region_name_Northern Metropolitan       8174 non-null   bool
 23  region_name_Northern Victoria           8174 non-null   bool
 24  region_name_South-Eastern Metropolitan  8174 non-null   bool
 25  region_name_Southern Metropolitan       8174 non-null   bool
 26  region_name_Western Metropolitan        8174 non-null   bool
dtypes: bool(13), float64(11), int32(2), int64(1)
memory usage: 997.8 KB

In [105]:
#actual ML starts here
X = df.drop(columns=['price'])
y = df['price']

In [109]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [110]:
from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2: 0.8411457209768544
MAE: 154453.13718654434

In [111]:
df

,rooms,price,distance,bedroom2,bathroom,car,land_size,building_area,year_built,latitude,...,method_SA,method_SP,method_VB,region_name_Eastern Metropolitan,region_name_Eastern Victoria,region_name_Northern Metropolitan,region_name_Northern Victoria,region_name_South-Eastern Metropolitan,region_name_Southern Metropolitan,region_name_Western Metropolitan
1,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,-37.80790,...,False,False,False,False,False,True,False,False,False,False
2,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,-37.80930,...,False,True,False,False,False,True,False,False,False,False
4,4,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,-37.80720,...,False,False,True,False,False,True,False,False,False,False
6,3,1876000.0,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,-37.80240,...,False,False,False,False,False,True,False,False,False,False
7,2,1636000.0,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,-37.80600,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,4,1245000.0,16.7,4.0,2.0,2.0,652.0,126.0,1981.0,-37.90562,...,False,False,False,False,False,False,False,True,False,False
13576,3,1031000.0,6.8,3.0,2.0,2.0,333.0,133.0,1995.0,-37.85927,...,False,True,False,False,False,False,False,False,False,True
13577,3,1170000.0,6.8,3.0,2.0,4.0,436.0,126.0,1997.0,-37.85274,...,False,False,False,False,False,False,False,False,False,True
13578,4,2500000.0,6.8,4.0,1.0,5.0,866.0,157.0,1920.0,-37.85908,...,False,False,False,False,False,False,False,False,False,True
13579,4,1285000.0,6.3,4.0,1.0,1.0,362.0,112.0,1920.0,-37.81188,...,False,True,False,False,False,False,False,False,False,True